default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: "postgres"
  password: "1234"
  timeout: 5000
  port: 5432

# test:
#   <<: *default
#   database: rh_system_test

development:
  <<: *default
  database: teletarifa_development

# staging:
#   adapter: postgresql
#   encoding: utf8
#   timeout: 5000
#   host: 
#   username: 
#   password: 
#   port: 5432
#   database: teletarifa_staging

# production:
#   adapter: postgresql
#   encoding: utf8
#   timeout: 5000
#   host: 
#   username: 
#   password: 
#   port: 5432
#   database: teletarifa_production